### ISSUE TITLE
 illumina, 1.8+

### ISSUE THREAD

**Issue by liyun831229** [brentp/bio-playground#12]
This script do not have illumina, 1.8+ ranging from 33-74

**Comment by liyun831229** [comment]
I forgot to mention which script...
https://github.com/brentp/bio-playground/blob/master/reads-utils/guess-encoding.py

**Comment by brentp** [comment]
can you open a PR?

**Comment by rwanwork** [comment]
I know it's been a few months but I've just opened a pull request -- hope it's ok!

**Comment by brentp** [comment]
Implemented by @rwanwork . Thanks!
