### ISSUE TITLE
Guessing heuristics

### ISSUE THREAD

**Issue by cviner** [brentp/bio-playground#18]
It is desirable to narrow down the possible encodings that [`guess-encoding.py`](https://github.com/brentp/bio-playground/blob/master/reads-utils/guess-encoding.py) produces, using heuristics beyond checking the min/max.

I have [added](https://github.com/cviner/bio-playground/commit/01c1af2211295a92be749bd539259f7ed99ed321) some to improve the ability to uniquely detect or eliminate Illumina 1.5 format, by considering the unused scores in that scheme and the frequency of the Illumina 1.5 "special" quality score (`B`).

I would be happy to work to integrate those [modifications](https://github.com/cviner/bio-playground/tree/improve_Illumina_1.5-heuristic) into this version, if there is interest in my doing so.

**Comment by cviner** [comment]
@brentp It'd be great to get your feedback on this.

All of these changes and some additions are, I believe, also now incorporated in [`seqkit`](https://github.com/shenwei356/seqkit/issues/18), which might provide a useful basis for comparisons (in either direction).

**Comment by brentp** [comment]
yes, if there's a certain way to narrow it down (e.g. by the `B` score) then it's fine to use that. I haven't looked at this for a long time so I'll trust your updates.

**Comment by cviner** [comment]
@brentp Yes, that's exactly right. This can fail, but my tests on such data showed high accuracy, though they were admittedly far from comprehensive.

Great—thanks! I'll fix conflicts for this branch and create a PR full it soon.

**Comment by cviner** [comment]
@brentp This is now ready to merge, at your convenience.

**Comment by cviner** [comment]
Resolved by PR #23.
