### ISSUE TITLE
URL BAM input

### ISSUE THREAD

**Issue by zetamui** [brentp/bio-playground#26]
Hi @brentp , I would like to ask, if there is a way to load BAM files from the working directory and not URLs (shown in the example)?

**Comment by brentp** [comment]
Hi, which example?

**Comment by zetamui** [comment]
> Hi, which example?

```
example usage:
        >>> igv = IGV()
        >>> igv.genome('hg19')
        'OK'
        #>>> igv.load('http://www.broadinstitute.org/igvdata/1KG/pilot2Bams/NA12878.SLX.bam')
        'OK'
        >>> igv.go('chr1:45,600-45,800')
        'OK'
    #save as svg, png, or jpg
        >>> igv.save('/tmp/r/region.svg')
        'OK'
        >>> igv.save('/tmp/r/region.png')
        'OK'
    # go to a gene name.
        >>> igv.go('muc5b')
        'OK'
        >>> igv.sort()
        'OK'
        >>> igv.save('muc5b.png')
        'OK'
    # get a list of commands that will work as an IGV batch script.
        >>> print "\n".join(igv.commands)
        snapshotDirectory /tmp/igv
        genome hg19
        goto chr1:45,600-45,800
        snapshotDirectory /tmp/r
        snapshot region.svg
        snapshot region.png
        goto muc5b
        sort base
        snapshot muc5b.png
    Note, there will be some delay as the browser has to load the annotations
    at each step.
```

This was an example shown in the documentation of the IGV class.

**Comment by brentp** [comment]
Hi, yes, you should be able to use: `./my.bam` as the argument to load.

**Comment by zetamui** [comment]
> Hi, yes, you should be able to use: `./my.bam` as the argument to load.

Hi @brentp , I tried using this command in the python interactive shell and it works no problem. However, if I want to use it in a python script, the load() function doesn't work:

```
Traceback (most recent call last):
  File "001_generateIGVPlotsFromAnnotatedVCF.py", line 22, in <module>
    igv = igv.load('./21-SCPv3-082-21UA023193-21S19817-15-MDv3_S2.sorted.dedupped.realigned.bam')
AttributeError: 'str' object has no attribute 'load'
```

Is there something I am missing?

**Comment by brentp** [comment]
Hi, in order to help you better, I'd have to see the full script. But, as you can see from the error message, at the time you call `igv.load`, the variable `igv` is a `str` not an `IGV` object as expected.

**Comment by zetamui** [comment]
> Hi, in order to help you better, I'd have to see the full script. But, as you can see from the error message, at the time you call `igv.load`, the variable `igv` is a `str` not an `IGV` object as expected.

Thanks a lot for pointing that out about the error message. I have mistakenly assigned the output of the previous statement igv.genome('hg19') to a variable called igv.
